### ISSUE TITLE
Decide how to handle a no-op step

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/factotum#12]
At least to start with, we want to exit with code 0 on the case of a no-op. My question is more: in the case of a no-op, do we behave `make -k`-style and process all other possible items before exiting ("lazy quit"), or do we just complete anything that was already running and quit ("eager quit").  I suppose the third option is we just kill anything else that is running ("rage quit").

Do we make this configurable on a per job basis?

**Comment by alexanderdean** [comment]
@ninjabear - having mulled this over, I think we go `make -k` style on no-op, for consistency with behavior on failure...

**Comment by ninjabear** [comment]
This is completed in [v0.1.0](https://github.com/snowplow/factotum/tree/0.1.0)
