### ISSUE TITLE
Deployment and setup

### ISSUE THREAD

**Issue by ninjabear** [snowplow/factotum#17]
As it's open source it's probably prudent to have a cursory look at how we'll do this. 

I think some of the good options are;

1. deb/rpm and a repository / ppa
   * `apt-get install factotum` 
2. bintray / zip of binaries
3. use cargo / distribute via source
   * `cargo install factotum`

I think 1. is the gold standard where possible, but it carries a bit of overhead and is very linux specific.

**Comment by alexanderdean** [comment]
Yes - 2 is closest to what we do today so I think we can start there...

**Comment by ninjabear** [comment]
We're using bintray!

This is completed in [v0.1.0](https://github.com/snowplow/factotum/tree/0.1.0)
