### ISSUE TITLE
Suggest renaming jobspec.rs to factfile.rs

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/factotum#24]
As jobspec sounds like it could be a test (spec) for a job...

**Comment by ninjabear** [comment]
There's a big refactor/rename incoming - will incorporate this @alexanderdean !

**Comment by alexanderdean** [comment]
EXCITING!

**Comment by ninjabear** [comment]
This is completed in [v0.1.0](https://github.com/snowplow/factotum/tree/0.1.0)
