### ISSUE TITLE
Add travis CI

### ISSUE THREAD

**Issue by ninjabear** [snowplow/factotum#25]
It's quite nice how they've done this with [serde](https://github.com/serde-rs/serde/blob/master/.travis.yml), using [travis-cargo](https://github.com/huonw/travis-cargo). Both travis and coveralls are free for open source projects.

**Comment by alexanderdean** [comment]
I've enabled Travis for this repo!

**Comment by ninjabear** [comment]
This issue now just covers Travis - the test coverage indicator is split off into #26

**Comment by ninjabear** [comment]
This is completed in [v0.1.0](https://github.com/snowplow/factotum/tree/0.1.0)
