### ISSUE TITLE
Placeholder for checking that onResult rules are always MECE

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/factotum#27]
This will need some code as it's inexpressible at the JSON Schema level.

**Comment by ninjabear** [comment]
This was completed as part of 0.1.0!

https://github.com/snowplow/factotum/blob/release/0.1.0/src/factotum/fileparser/mod.rs#L116-L124
https://github.com/snowplow/factotum/blob/release/0.1.0/src/factotum/fileparser/tests.rs#L65-L85

Perhaps there's more to it?

**Comment by alexanderdean** [comment]
Ace, closing!
