### ISSUE TITLE
Use .factfile as file extension in README and all tests and samples

### ISSUE THREAD

**Issue by ninjabear** [snowplow/factotum#34]
Should factotum facfiles be:
- .factotum
- .factfile
- .fact
- .job
- .ff 
- .json (this one is unrelated, but it makes sure most editors pick it up as json)
- something else?

**Comment by alexanderdean** [comment]
Hmm, I hadn't thought of `.json`! It has some merit...

**Comment by alexanderdean** [comment]
We ended up standardising on `.factfile`

**Comment by ninjabear** [comment]
### Sublist of places that need converting (ticks for is done):

- [ ] tests
- [ ] samples
- [ ] codebase/comments
- [ ] wiki
- [ ] readme
