### ISSUE TITLE
Add --validate command to validate factfiles

### ISSUE THREAD

**Issue by ninjabear** [snowplow/factotum#38]

**Comment by ninjabear** [comment]
This could also be "dry-run"

**Comment by alexanderdean** [comment]
Instead of a `--validate`, I'd probably go for the Docker/AWS CLI approach of sub-commands, so:

```
factotum run
factotum validate
factotum ...
```

Kind of thing. This gives a lot more space for the tool to "grow" than adding more and more opt flags...

**Comment by alexanderdean** [comment]
To me validate and dry-run are slightly different:

1. A validate is the kind of thing you might add into CI (i.e. it's machine-friendly)
2. A dry-run would validate but would also step through the tasks and "pretend" to run them. I'd imagine that's more useful for a human trying to visually verify their DAG

**Comment by ninjabear** [comment]
Agree with both your comments - my thoughts with "dry-run" were that for in order for it to complete, it has to be valid too - but it'd be nice to split them up for those two use cases

**Comment by alexanderdean** [comment]
Hasn't this been done @ninjabear ?

**Comment by ninjabear** [comment]
Hey @alexanderdean ! This is a duplicate of #68, it has been done there. Closing!
