### ISSUE TITLE
Add support for run constraints

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/factotum#45]
This is the idea that Factotum should only execute if a "run constraint" specified on the CLI resolves to true.

This is a powerful feature (taken from Snowplow's internal executor), which lets you have the same Factotum invocation in the cron on multiple boxes, but only one box will execute the job.

Example cronfile:

``` cron
BOX1=box1.acme.internal
BOX2=box2.acme.internal

/opt/factotum-0.4.0/factotum first-dag.factotum --constraint "host,${BOX1}"
/opt/factotum-0.4.0/factotum secnd-dag.factotum --constraint "host,${BOX2}"
```

To start with, we only allow one constraint, and the only allowed constraint is `host`, and the implied check is `==`.

**Comment by ninjabear** [comment]
Hey!

This functionality can be reproduced like this:

```{json}
{
    "schema": "iglu:com.snowplowanalytics.factotum/factfile/jsonschema/1-0-0",
    "data": {
        "name": "constraint demo",
        "tasks": [
            {
                "name": "box check",
                "executor": "shell",
                "command": "if [ \"{{box_name}}\" = \"1\" ]; then exit 1; else exit 0; fi",
                "arguments": [],
                "dependsOn": [],
                "onResult": {
                    "terminateJobWithSuccess": [ 0 ],
                    "continueJob": [ 1 ]
                }
            },
            {
                "name": "execute",
                "executor": "shell",
                "command": "echo",
                "arguments": [ "beta" ],
                "dependsOn": [ "box check" ],
                "onResult": {
                    "terminateJobWithSuccess": [ 3 ],
                    "continueJob": [ 0 ]
                }
            }
        ]
    }
}
```

and running like this:

```{bash}
factotum run ./noop_constraint.factfile --env '{"box_name": "1"}'
```

This may not be specific enough for this use-case, but I thought I'd mention this anyway

**Comment by alexanderdean** [comment]
Hey @ninjabear - that's really neat. An emergent property of Factotum!

I think we need to keep this as a feature however, because otherwise we have to mutate all of our factfiles to add this check...
