### ISSUE TITLE
Rename run job command

### ISSUE THREAD

**Issue by ihortom** [snowplow/factotum#67]
The "run job" command is meant to (re-)run jobs for a client. It doesn't sound semantically right "run job for {{job}}". It could be appropriate if there was only one job per client, hence "run job for {{client}}" but not in this case.

Moreover, removing "for" will also shorten the command, which is almost always a good thing.

**Comment by ninjabear** [comment]
I think this is a ticket for Snowdroid @ihortom? Factotum runs look like this:

```
$ factotum samples/echo.factotum --start "echo beta"
```

**Comment by ihortom** [comment]
@ninjabear - you are right, sorry. Migrating to Snowdroid
