### ISSUE TITLE
Add validate command

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/factotum#68]
Which will validate the Factfile against the factfile schema (and verify that the factfile schema is a Factotum file! not a random JSON Schema)

**Comment by alexanderdean** [comment]
This is so that Leon and Ihor can validate their Factfiles before pushing.

**Comment by ninjabear** [comment]
I added this command as `factotum validate <factfile>` rather than `lint` as lint to me suggests that it'll tidy up the factfile for you too.

Any thoughts on this @alexanderdean @leonmaas @ihortom?

**Comment by alexanderdean** [comment]
Sounds good, `lint` is perhaps a bit jargony
