### ISSUE TITLE
Add support for attaching tags at runtime over the CLI

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/factotum#77]

**Comment by ninjabear** [comment]
Advanced to 0.3.0, this feature is essential as part of #59

**Comment by ninjabear** [comment]
I've added a command line option `--tag=key,value` that has the following effects:

1) it's used to calculate the "job reference" (SHA256) hash
2) all tags are passed through in the webhook as a list of key -> value pairs under a "tags" object, e.g.

```$ factotum run samples/echo.factfile --webhook http://*** --tag="foo,bar" --tag="foo2,bar2"```

results in the following structure being inserted at the root level of the webhook update json (job and task level)

```
...
"tags":{"foo":"bar","foo2":"bar2"}
...
```

**Comment by alexanderdean** [comment]
Perfect!
