### ISSUE TITLE
Broken links in README

### ISSUE THREAD

**Issue by chuwy** [snowplow/factotum#78]
Links to echo.factfile and sleep.factfile referring to 0.2.0 branch, which is deleted. They will also be broken in 0.3.0 when according branch will be deleted.

**Comment by ninjabear** [comment]
Hey @chuwy ! The readme was updated as part of this https://github.com/snowplow/factotum/issues/34, I think the changes for `.factfile are all in the 0.3.0 release [here](https://github.com/snowplow/factotum/blob/release/0.3.0/README.md). Have I missed some?

**Comment by chuwy** [comment]
Hey! I think you'll need to change `release/0.3.0` (or `0.2.0` whatever) part of URL to `master`. Because as soon as you delete `release/0.3.0` branch - URLs will be 404. 

If you click on `sleep.factotum` link in current master's README you'll get [404](https://raw.githubusercontent.com/snowplow/factotum/release/0.2.0/samples/sleep.factotum). Same will happen with upcoming 0.3.0.

**Comment by ninjabear** [comment]
Ah! I see what you mean! Thanks!
