### ISSUE TITLE
Add "transition" information to webhook output

### ISSUE THREAD

**Issue by ninjabear** [snowplow/factotum#82]
Splitting up updates into "task_updates" and "job_updates".

Job updates contain the previous state, and the current state (this change is the reason the event was emitted) (e.g. RUNNING->SUCCEEDED)

Task updates contain a list of task transitions (the reason for the event to be emitted) e.g. RUNNING->SUCCEEDED_NO_OP

**Comment by ninjabear** [comment]
Essential as part of #59

**Comment by alexanderdean** [comment]
Is this a ticket @ninjabear - the webhook is new in 0.3.0, so isn't this just part of the #59 commit?

**Comment by ninjabear** [comment]
In between this and the commit for #59 the code went through a linter, so it's going to be really hard to put this back there. 

I think given that, this is the best way to represent the series of events that happened to the code-base

**Comment by alexanderdean** [comment]
Okay, fair play
