### ISSUE TITLE
Add validation of factfile

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/factotum#9]
Using https://github.com/snowplow/iglu-rust-client

**Comment by ninjabear** [comment]
@alexanderdean - is this ticket still valid? We are validating factfiles using [Valico](https://github.com/rustless/valico)

**Comment by alexanderdean** [comment]
Sounds like we have done it then?

**Comment by ninjabear** [comment]
We have, just without creating "iglu-rust-client" https://github.com/snowplow/iglu-rust-client. Was this just the original idea or is it something we'll start to look at later?

**Comment by alexanderdean** [comment]
I think what we have is fine, closing
