### ISSUE TITLE
factotum dot : overwrite flag not consistent

### ISSUE THREAD

**Issue by nlehuby** [snowplow/factotum#97]
When you use the `--overwrite` flag in a `factotum dot` command, you get a confusing error if the file does not exist yet.
It would be better if the flag overwrites the file if it already exists and creates it if not.

For now, this flag seems pretty useless as you have to check if the file already exist to know if you need to apply the flag.

**Comment by ninjabear** [comment]
Hi @nlehuby,

You're quite right - it would be better to work in the way you suggest! I'll add this into the next release.

For now as a workaround - using `factotum dot` without the `--output` option prints the dotfile to stdout. This can be piped to a file for the same result, for example:

`factotum dot samples/echo.factfile > myoutput.dot`
