### ISSUE TITLE
Add "server mode" to Factotum

### ISSUE THREAD

**Issue by ninjabear** [snowplow/factotum#98]
We need to create a daemon that can accept jobs remotely and start them immediately.

This can be called "factotumd", "factotum server" or another snazzy name (this may change).

We should stick to a process boundary for now (ie. the server should use [child processes](http://rustbyexample.com/std_misc/process.html) of the factotum cli tool) to execute jobs. This could change at a later date.

The intent behind this is to permit starting (pre-shared) factotum jobs on a remote machine, so a user wouldn't need to ssh in and run it manually, and as a springboard for later work in creating a whole server-based factotum ecosystem.

/cc @alexanderdean

**Comment by alexanderdean** [comment]
To come: update description to include Consul behaviors.

**Comment by ungn** [comment]
Closing as changes have been made in separate [factotum-server project](https://github.com/snowplow/factotum-server).
